#!/bin/bash
#PBS -lwalltime=08:00:00
#PBS -lselect=1:ncpus=8:mem=32gb

module load miniforge/3
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate Env

chip_dir=/rds/general/project/diantonio/live/Yaryna/ChIP_WT
index=/rds/general/project/diantonio/live/Yaryna/genome/hg38

bowtie2 -x $index \
    -1 $chip_dir/CS1AN_WT_BG4_Bio1_Tech1_R1.fq.gz \
    -2 $chip_dir/CS1AN_WT_BG4_Bio1_Tech1_R2.fq.gz \
    -S $chip_dir/CS1AN_WT_BG4_Bio1_Tech1.sam \
    2> $chip_dir/CS1AN_WT_BG4_Bio1_Tech1.bowtie2.txt

bowtie2 -x $index \
    -1 $chip_dir/CS1AN_WT_BG4_Bio1_Tech2_R1.fq.gz \
    -2 $chip_dir/CS1AN_WT_BG4_Bio1_Tech2_R2.fq.gz \
    -S $chip_dir/CS1AN_WT_BG4_Bio1_Tech2.sam \
    2> $chip_dir/CS1AN_WT_BG4_Bio1_Tech2.bowtie2.txt

bowtie2 -x $index \
    -1 $chip_dir/CS1AN_WT_Input_Bio1_R1.fq.gz \
    -2 $chip_dir/CS1AN_WT_Input_Bio1_R2.fq.gz \
    -S $chip_dir/CS1AN_WT_Input_Bio1.sam \
    2> $chip_dir/CS1AN_WT_Input_Bio1.bowtie2.txt
